#ifndef EKRAN_H
#define EKRAN_H

// OLED Animation: flower
// Code auto-generated by https://wokwi.com/animator, graphics by icons8.com

#include <Arduino.h>
#include <vector>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include "ir.h"

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define OLED_ADDR 0x3C
#define IR_RECV_PIN 5 
#define IR_SEND_PIN 17

extern Adafruit_SSD1306 display;

#define FRAME_DELAY (42)
#define FRAME_WIDTH (48)
#define FRAME_HEIGHT (48)
#define FRAME_COUNT (sizeof(frames) / sizeof(frames[0]))

enum ScreenState {
    SCREEN_MAIN_MENU,
    SCREEN_IR_RECEIVER,
    SCREEN_IR_EMISSION,
    SCREEN_GAME
};


class Ekran{
public:
ScreenState currentScreen = SCREEN_MAIN_MENU;
static const byte frameCount;
static bool firstScreen;
std::vector <String> ListMainMenu;
int playerX = 50;
int playerY = 50;
int obstacleX = 30;
int obstacleY = 12;
double score=0;

  Ekran();
  void begin();
  void pocetni();
  void brisi();
  void DrawMeni(ScreenState currentScreen, int s, bool saveIR, int index,bool sendIR, bool moveRight, bool moveLeft);
  void MainMeni(int s);
  void IrReciver(bool save);
  void IrEmission(int index, bool send);
  void Game(bool moveRight, bool moveLeft);
  bool checkCollision(int px, int py, int pw, int ph, int ox, int oy, int ow, int oh);

private:
    int frame=0;
    Ir ir;
    unsigned long lastIrRead=0;

};


#endif